name: Existentials on a leash

plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings

remote_theme: "jekyll/minima@4de3223"

minima:
  skin: dark

titles_from_headings:
  enabled:     true
  strip_title: true
